language: node_js
node_js: "10"
jobs:
  include:
    - stage: "Tests & coverage"
      before_install:
        - travis_retry yarn global add codecov
      install:
        - travis_retry yarn install
      script:
        - yarn format
        - yarn lint
        - yarn test
        - yarn build
        - yarn doc
        - codecov
    - stage: "Tests & coverage"
      install:
        - yarn install
      cache:
        directories:
          - "$HOME/.yarn-cache"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs/
  target-branch: gh-pages
  on:
    branch: master
