language: node_js
node_js: "8"
install:
- travis_retry npm install -g codecov
- travis_retry npm install
script:
- npm run format
- npm run lint
- npm run test
- npm run build
- npm run doc
- codecov
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs/
  target-branch: gh-pages
  on:
    branch: master
